
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const WorkspaceUserRole = {
  MEMBER: 'MEMBER',
  ADMIN: 'ADMIN',
  GUEST: 'GUEST'
} as const

export type WorkspaceUserRole = (typeof WorkspaceUserRole)[keyof typeof WorkspaceUserRole]


export const INVITATION_TYPE = {
  WORKSPACE: 'WORKSPACE',
  CHANNEL: 'CHANNEL'
} as const

export type INVITATION_TYPE = (typeof INVITATION_TYPE)[keyof typeof INVITATION_TYPE]


export const INVITE_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED'
} as const

export type INVITE_STATUS = (typeof INVITE_STATUS)[keyof typeof INVITE_STATUS]
