
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkspaceUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorkspaceUser
 * 
 */
export type WorkspaceUserModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkspaceUserPayload>

export type AggregateWorkspaceUser = {
  _count: WorkspaceUserCountAggregateOutputType | null
  _min: WorkspaceUserMinAggregateOutputType | null
  _max: WorkspaceUserMaxAggregateOutputType | null
}

export type WorkspaceUserMinAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  userId: string | null
  role: $Enums.WorkspaceUserRole | null
  joinedAt: Date | null
}

export type WorkspaceUserMaxAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  userId: string | null
  role: $Enums.WorkspaceUserRole | null
  joinedAt: Date | null
}

export type WorkspaceUserCountAggregateOutputType = {
  id: number
  workspaceId: number
  userId: number
  role: number
  joinedAt: number
  _all: number
}


export type WorkspaceUserMinAggregateInputType = {
  id?: true
  workspaceId?: true
  userId?: true
  role?: true
  joinedAt?: true
}

export type WorkspaceUserMaxAggregateInputType = {
  id?: true
  workspaceId?: true
  userId?: true
  role?: true
  joinedAt?: true
}

export type WorkspaceUserCountAggregateInputType = {
  id?: true
  workspaceId?: true
  userId?: true
  role?: true
  joinedAt?: true
  _all?: true
}

export type WorkspaceUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkspaceUser to aggregate.
   */
  where?: Prisma.WorkspaceUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkspaceUsers to fetch.
   */
  orderBy?: Prisma.WorkspaceUserOrderByWithRelationInput | Prisma.WorkspaceUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkspaceUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkspaceUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkspaceUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkspaceUsers
  **/
  _count?: true | WorkspaceUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkspaceUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkspaceUserMaxAggregateInputType
}

export type GetWorkspaceUserAggregateType<T extends WorkspaceUserAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkspaceUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkspaceUser[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkspaceUser[P]>
}




export type WorkspaceUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkspaceUserWhereInput
  orderBy?: Prisma.WorkspaceUserOrderByWithAggregationInput | Prisma.WorkspaceUserOrderByWithAggregationInput[]
  by: Prisma.WorkspaceUserScalarFieldEnum[] | Prisma.WorkspaceUserScalarFieldEnum
  having?: Prisma.WorkspaceUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkspaceUserCountAggregateInputType | true
  _min?: WorkspaceUserMinAggregateInputType
  _max?: WorkspaceUserMaxAggregateInputType
}

export type WorkspaceUserGroupByOutputType = {
  id: string
  workspaceId: string
  userId: string
  role: $Enums.WorkspaceUserRole
  joinedAt: Date
  _count: WorkspaceUserCountAggregateOutputType | null
  _min: WorkspaceUserMinAggregateOutputType | null
  _max: WorkspaceUserMaxAggregateOutputType | null
}

export type GetWorkspaceUserGroupByPayload<T extends WorkspaceUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkspaceUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkspaceUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkspaceUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkspaceUserGroupByOutputType[P]>
      }
    >
  >



export type WorkspaceUserWhereInput = {
  AND?: Prisma.WorkspaceUserWhereInput | Prisma.WorkspaceUserWhereInput[]
  OR?: Prisma.WorkspaceUserWhereInput[]
  NOT?: Prisma.WorkspaceUserWhereInput | Prisma.WorkspaceUserWhereInput[]
  id?: Prisma.StringFilter<"WorkspaceUser"> | string
  workspaceId?: Prisma.StringFilter<"WorkspaceUser"> | string
  userId?: Prisma.StringFilter<"WorkspaceUser"> | string
  role?: Prisma.EnumWorkspaceUserRoleFilter<"WorkspaceUser"> | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFilter<"WorkspaceUser"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  messageSender?: Prisma.MessageListRelationFilter
  workspaceChannel?: Prisma.WorkspaceChannelListRelationFilter
  dmGroups?: Prisma.DMGroupListRelationFilter
  dmGroupsCreated?: Prisma.DMGroupListRelationFilter
}

export type WorkspaceUserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  messageSender?: Prisma.MessageOrderByRelationAggregateInput
  workspaceChannel?: Prisma.WorkspaceChannelOrderByRelationAggregateInput
  dmGroups?: Prisma.DMGroupOrderByRelationAggregateInput
  dmGroupsCreated?: Prisma.DMGroupOrderByRelationAggregateInput
}

export type WorkspaceUserWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  workspaceId_userId?: Prisma.WorkspaceUserWorkspaceIdUserIdCompoundUniqueInput
  AND?: Prisma.WorkspaceUserWhereInput | Prisma.WorkspaceUserWhereInput[]
  OR?: Prisma.WorkspaceUserWhereInput[]
  NOT?: Prisma.WorkspaceUserWhereInput | Prisma.WorkspaceUserWhereInput[]
  workspaceId?: Prisma.StringFilter<"WorkspaceUser"> | string
  userId?: Prisma.StringFilter<"WorkspaceUser"> | string
  role?: Prisma.EnumWorkspaceUserRoleFilter<"WorkspaceUser"> | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFilter<"WorkspaceUser"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  messageSender?: Prisma.MessageListRelationFilter
  workspaceChannel?: Prisma.WorkspaceChannelListRelationFilter
  dmGroups?: Prisma.DMGroupListRelationFilter
  dmGroupsCreated?: Prisma.DMGroupListRelationFilter
}, "id" | "workspaceId_userId">

export type WorkspaceUserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
  _count?: Prisma.WorkspaceUserCountOrderByAggregateInput
  _max?: Prisma.WorkspaceUserMaxOrderByAggregateInput
  _min?: Prisma.WorkspaceUserMinOrderByAggregateInput
}

export type WorkspaceUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkspaceUserScalarWhereWithAggregatesInput | Prisma.WorkspaceUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkspaceUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkspaceUserScalarWhereWithAggregatesInput | Prisma.WorkspaceUserScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkspaceUser"> | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"WorkspaceUser"> | string
  userId?: Prisma.StringWithAggregatesFilter<"WorkspaceUser"> | string
  role?: Prisma.EnumWorkspaceUserRoleWithAggregatesFilter<"WorkspaceUser"> | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeWithAggregatesFilter<"WorkspaceUser"> | Date | string
}

export type WorkspaceUserCreateInput = {
  id?: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutWorkspaceUsersInput
  user: Prisma.UserCreateNestedOneWithoutWorkspaceUsersInput
  messageSender?: Prisma.MessageCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserUncheckedCreateInput = {
  id?: string
  workspaceId: string
  userId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  messageSender?: Prisma.MessageUncheckedCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  messageSender?: Prisma.MessageUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messageSender?: Prisma.MessageUncheckedUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserCreateManyInput = {
  id?: string
  workspaceId: string
  userId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
}

export type WorkspaceUserUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkspaceUserUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkspaceUserListRelationFilter = {
  every?: Prisma.WorkspaceUserWhereInput
  some?: Prisma.WorkspaceUserWhereInput
  none?: Prisma.WorkspaceUserWhereInput
}

export type WorkspaceUserOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkspaceUserWorkspaceIdUserIdCompoundUniqueInput = {
  workspaceId: string
  userId: string
}

export type WorkspaceUserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
}

export type WorkspaceUserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
}

export type WorkspaceUserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  joinedAt?: Prisma.SortOrder
}

export type WorkspaceUserScalarRelationFilter = {
  is?: Prisma.WorkspaceUserWhereInput
  isNot?: Prisma.WorkspaceUserWhereInput
}

export type WorkspaceUserCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutUserInput, Prisma.WorkspaceUserUncheckedCreateWithoutUserInput> | Prisma.WorkspaceUserCreateWithoutUserInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutUserInput | Prisma.WorkspaceUserCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.WorkspaceUserCreateManyUserInputEnvelope
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
}

export type WorkspaceUserUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutUserInput, Prisma.WorkspaceUserUncheckedCreateWithoutUserInput> | Prisma.WorkspaceUserCreateWithoutUserInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutUserInput | Prisma.WorkspaceUserCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.WorkspaceUserCreateManyUserInputEnvelope
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
}

export type WorkspaceUserUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutUserInput, Prisma.WorkspaceUserUncheckedCreateWithoutUserInput> | Prisma.WorkspaceUserCreateWithoutUserInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutUserInput | Prisma.WorkspaceUserCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutUserInput | Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.WorkspaceUserCreateManyUserInputEnvelope
  set?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  delete?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  update?: Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutUserInput | Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.WorkspaceUserUpdateManyWithWhereWithoutUserInput | Prisma.WorkspaceUserUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
}

export type WorkspaceUserUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutUserInput, Prisma.WorkspaceUserUncheckedCreateWithoutUserInput> | Prisma.WorkspaceUserCreateWithoutUserInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutUserInput | Prisma.WorkspaceUserCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutUserInput | Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.WorkspaceUserCreateManyUserInputEnvelope
  set?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  delete?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  update?: Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutUserInput | Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.WorkspaceUserUpdateManyWithWhereWithoutUserInput | Prisma.WorkspaceUserUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
}

export type WorkspaceUserCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkspaceUserCreateWithoutWorkspaceInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceInput | Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.WorkspaceUserCreateManyWorkspaceInputEnvelope
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
}

export type WorkspaceUserUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkspaceUserCreateWithoutWorkspaceInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceInput | Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.WorkspaceUserCreateManyWorkspaceInputEnvelope
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
}

export type WorkspaceUserUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkspaceUserCreateWithoutWorkspaceInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceInput | Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.WorkspaceUserCreateManyWorkspaceInputEnvelope
  set?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  delete?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  update?: Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.WorkspaceUserUpdateManyWithWhereWithoutWorkspaceInput | Prisma.WorkspaceUserUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
}

export type WorkspaceUserUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput> | Prisma.WorkspaceUserCreateWithoutWorkspaceInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceInput | Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.WorkspaceUserCreateManyWorkspaceInputEnvelope
  set?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  delete?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  update?: Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.WorkspaceUserUpdateManyWithWhereWithoutWorkspaceInput | Prisma.WorkspaceUserUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
}

export type EnumWorkspaceUserRoleFieldUpdateOperationsInput = {
  set?: $Enums.WorkspaceUserRole
}

export type WorkspaceUserCreateNestedManyWithoutWorkspaceChannelInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput> | Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput | Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
}

export type WorkspaceUserUncheckedCreateNestedManyWithoutWorkspaceChannelInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput> | Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput | Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
}

export type WorkspaceUserUpdateManyWithoutWorkspaceChannelNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput> | Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput | Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput[]
  upsert?: Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceChannelInput | Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceChannelInput[]
  set?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  delete?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  update?: Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceChannelInput | Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceChannelInput[]
  updateMany?: Prisma.WorkspaceUserUpdateManyWithWhereWithoutWorkspaceChannelInput | Prisma.WorkspaceUserUpdateManyWithWhereWithoutWorkspaceChannelInput[]
  deleteMany?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
}

export type WorkspaceUserUncheckedUpdateManyWithoutWorkspaceChannelNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput> | Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput | Prisma.WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput[]
  upsert?: Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceChannelInput | Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceChannelInput[]
  set?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  delete?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  update?: Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceChannelInput | Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceChannelInput[]
  updateMany?: Prisma.WorkspaceUserUpdateManyWithWhereWithoutWorkspaceChannelInput | Prisma.WorkspaceUserUpdateManyWithWhereWithoutWorkspaceChannelInput[]
  deleteMany?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
}

export type WorkspaceUserCreateNestedOneWithoutMessageSenderInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutMessageSenderInput, Prisma.WorkspaceUserUncheckedCreateWithoutMessageSenderInput>
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutMessageSenderInput
  connect?: Prisma.WorkspaceUserWhereUniqueInput
}

export type WorkspaceUserUpdateOneRequiredWithoutMessageSenderNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutMessageSenderInput, Prisma.WorkspaceUserUncheckedCreateWithoutMessageSenderInput>
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutMessageSenderInput
  upsert?: Prisma.WorkspaceUserUpsertWithoutMessageSenderInput
  connect?: Prisma.WorkspaceUserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkspaceUserUpdateToOneWithWhereWithoutMessageSenderInput, Prisma.WorkspaceUserUpdateWithoutMessageSenderInput>, Prisma.WorkspaceUserUncheckedUpdateWithoutMessageSenderInput>
}

export type WorkspaceUserCreateNestedManyWithoutDmGroupsInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput> | Prisma.WorkspaceUserCreateWithoutDmGroupsInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsInput | Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
}

export type WorkspaceUserCreateNestedOneWithoutDmGroupsCreatedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsCreatedInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsCreatedInput>
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsCreatedInput
  connect?: Prisma.WorkspaceUserWhereUniqueInput
}

export type WorkspaceUserUncheckedCreateNestedManyWithoutDmGroupsInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput> | Prisma.WorkspaceUserCreateWithoutDmGroupsInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsInput | Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
}

export type WorkspaceUserUpdateManyWithoutDmGroupsNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput> | Prisma.WorkspaceUserCreateWithoutDmGroupsInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsInput | Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsInput[]
  upsert?: Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutDmGroupsInput | Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutDmGroupsInput[]
  set?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  delete?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  update?: Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutDmGroupsInput | Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutDmGroupsInput[]
  updateMany?: Prisma.WorkspaceUserUpdateManyWithWhereWithoutDmGroupsInput | Prisma.WorkspaceUserUpdateManyWithWhereWithoutDmGroupsInput[]
  deleteMany?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
}

export type WorkspaceUserUpdateOneRequiredWithoutDmGroupsCreatedNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsCreatedInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsCreatedInput>
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsCreatedInput
  upsert?: Prisma.WorkspaceUserUpsertWithoutDmGroupsCreatedInput
  connect?: Prisma.WorkspaceUserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkspaceUserUpdateToOneWithWhereWithoutDmGroupsCreatedInput, Prisma.WorkspaceUserUpdateWithoutDmGroupsCreatedInput>, Prisma.WorkspaceUserUncheckedUpdateWithoutDmGroupsCreatedInput>
}

export type WorkspaceUserUncheckedUpdateManyWithoutDmGroupsNestedInput = {
  create?: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput> | Prisma.WorkspaceUserCreateWithoutDmGroupsInput[] | Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput[]
  connectOrCreate?: Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsInput | Prisma.WorkspaceUserCreateOrConnectWithoutDmGroupsInput[]
  upsert?: Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutDmGroupsInput | Prisma.WorkspaceUserUpsertWithWhereUniqueWithoutDmGroupsInput[]
  set?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  disconnect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  delete?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  connect?: Prisma.WorkspaceUserWhereUniqueInput | Prisma.WorkspaceUserWhereUniqueInput[]
  update?: Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutDmGroupsInput | Prisma.WorkspaceUserUpdateWithWhereUniqueWithoutDmGroupsInput[]
  updateMany?: Prisma.WorkspaceUserUpdateManyWithWhereWithoutDmGroupsInput | Prisma.WorkspaceUserUpdateManyWithWhereWithoutDmGroupsInput[]
  deleteMany?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
}

export type WorkspaceUserCreateWithoutUserInput = {
  id?: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutWorkspaceUsersInput
  messageSender?: Prisma.MessageCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserUncheckedCreateWithoutUserInput = {
  id?: string
  workspaceId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  messageSender?: Prisma.MessageUncheckedCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserCreateOrConnectWithoutUserInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutUserInput, Prisma.WorkspaceUserUncheckedCreateWithoutUserInput>
}

export type WorkspaceUserCreateManyUserInputEnvelope = {
  data: Prisma.WorkspaceUserCreateManyUserInput | Prisma.WorkspaceUserCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type WorkspaceUserUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutUserInput, Prisma.WorkspaceUserUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutUserInput, Prisma.WorkspaceUserUncheckedCreateWithoutUserInput>
}

export type WorkspaceUserUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutUserInput, Prisma.WorkspaceUserUncheckedUpdateWithoutUserInput>
}

export type WorkspaceUserUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.WorkspaceUserScalarWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateManyMutationInput, Prisma.WorkspaceUserUncheckedUpdateManyWithoutUserInput>
}

export type WorkspaceUserScalarWhereInput = {
  AND?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
  OR?: Prisma.WorkspaceUserScalarWhereInput[]
  NOT?: Prisma.WorkspaceUserScalarWhereInput | Prisma.WorkspaceUserScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkspaceUser"> | string
  workspaceId?: Prisma.StringFilter<"WorkspaceUser"> | string
  userId?: Prisma.StringFilter<"WorkspaceUser"> | string
  role?: Prisma.EnumWorkspaceUserRoleFilter<"WorkspaceUser"> | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFilter<"WorkspaceUser"> | Date | string
}

export type WorkspaceUserCreateWithoutWorkspaceInput = {
  id?: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutWorkspaceUsersInput
  messageSender?: Prisma.MessageCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserUncheckedCreateWithoutWorkspaceInput = {
  id?: string
  userId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  messageSender?: Prisma.MessageUncheckedCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput>
}

export type WorkspaceUserCreateManyWorkspaceInputEnvelope = {
  data: Prisma.WorkspaceUserCreateManyWorkspaceInput | Prisma.WorkspaceUserCreateManyWorkspaceInput[]
  skipDuplicates?: boolean
}

export type WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutWorkspaceInput, Prisma.WorkspaceUserUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceInput>
}

export type WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutWorkspaceInput, Prisma.WorkspaceUserUncheckedUpdateWithoutWorkspaceInput>
}

export type WorkspaceUserUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.WorkspaceUserScalarWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateManyMutationInput, Prisma.WorkspaceUserUncheckedUpdateManyWithoutWorkspaceInput>
}

export type WorkspaceUserCreateWithoutWorkspaceChannelInput = {
  id?: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutWorkspaceUsersInput
  user: Prisma.UserCreateNestedOneWithoutWorkspaceUsersInput
  messageSender?: Prisma.MessageCreateNestedManyWithoutSenderUserInput
  dmGroups?: Prisma.DMGroupCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput = {
  id?: string
  workspaceId: string
  userId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  messageSender?: Prisma.MessageUncheckedCreateNestedManyWithoutSenderUserInput
  dmGroups?: Prisma.DMGroupUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserCreateOrConnectWithoutWorkspaceChannelInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput>
}

export type WorkspaceUserUpsertWithWhereUniqueWithoutWorkspaceChannelInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutWorkspaceChannelInput, Prisma.WorkspaceUserUncheckedUpdateWithoutWorkspaceChannelInput>
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutWorkspaceChannelInput, Prisma.WorkspaceUserUncheckedCreateWithoutWorkspaceChannelInput>
}

export type WorkspaceUserUpdateWithWhereUniqueWithoutWorkspaceChannelInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutWorkspaceChannelInput, Prisma.WorkspaceUserUncheckedUpdateWithoutWorkspaceChannelInput>
}

export type WorkspaceUserUpdateManyWithWhereWithoutWorkspaceChannelInput = {
  where: Prisma.WorkspaceUserScalarWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateManyMutationInput, Prisma.WorkspaceUserUncheckedUpdateManyWithoutWorkspaceChannelInput>
}

export type WorkspaceUserCreateWithoutMessageSenderInput = {
  id?: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutWorkspaceUsersInput
  user: Prisma.UserCreateNestedOneWithoutWorkspaceUsersInput
  workspaceChannel?: Prisma.WorkspaceChannelCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserUncheckedCreateWithoutMessageSenderInput = {
  id?: string
  workspaceId: string
  userId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserCreateOrConnectWithoutMessageSenderInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutMessageSenderInput, Prisma.WorkspaceUserUncheckedCreateWithoutMessageSenderInput>
}

export type WorkspaceUserUpsertWithoutMessageSenderInput = {
  update: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutMessageSenderInput, Prisma.WorkspaceUserUncheckedUpdateWithoutMessageSenderInput>
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutMessageSenderInput, Prisma.WorkspaceUserUncheckedCreateWithoutMessageSenderInput>
  where?: Prisma.WorkspaceUserWhereInput
}

export type WorkspaceUserUpdateToOneWithWhereWithoutMessageSenderInput = {
  where?: Prisma.WorkspaceUserWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutMessageSenderInput, Prisma.WorkspaceUserUncheckedUpdateWithoutMessageSenderInput>
}

export type WorkspaceUserUpdateWithoutMessageSenderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateWithoutMessageSenderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserCreateWithoutDmGroupsInput = {
  id?: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutWorkspaceUsersInput
  user: Prisma.UserCreateNestedOneWithoutWorkspaceUsersInput
  messageSender?: Prisma.MessageCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserUncheckedCreateWithoutDmGroupsInput = {
  id?: string
  workspaceId: string
  userId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  messageSender?: Prisma.MessageUncheckedCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedCreateNestedManyWithoutCreatedByUserInput
}

export type WorkspaceUserCreateOrConnectWithoutDmGroupsInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput>
}

export type WorkspaceUserCreateWithoutDmGroupsCreatedInput = {
  id?: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutWorkspaceUsersInput
  user: Prisma.UserCreateNestedOneWithoutWorkspaceUsersInput
  messageSender?: Prisma.MessageCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupCreateNestedManyWithoutWorkspaceUsersInput
}

export type WorkspaceUserUncheckedCreateWithoutDmGroupsCreatedInput = {
  id?: string
  workspaceId: string
  userId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
  messageSender?: Prisma.MessageUncheckedCreateNestedManyWithoutSenderUserInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedCreateNestedManyWithoutWorkspaceUsersInput
  dmGroups?: Prisma.DMGroupUncheckedCreateNestedManyWithoutWorkspaceUsersInput
}

export type WorkspaceUserCreateOrConnectWithoutDmGroupsCreatedInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsCreatedInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsCreatedInput>
}

export type WorkspaceUserUpsertWithWhereUniqueWithoutDmGroupsInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutDmGroupsInput, Prisma.WorkspaceUserUncheckedUpdateWithoutDmGroupsInput>
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsInput>
}

export type WorkspaceUserUpdateWithWhereUniqueWithoutDmGroupsInput = {
  where: Prisma.WorkspaceUserWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutDmGroupsInput, Prisma.WorkspaceUserUncheckedUpdateWithoutDmGroupsInput>
}

export type WorkspaceUserUpdateManyWithWhereWithoutDmGroupsInput = {
  where: Prisma.WorkspaceUserScalarWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateManyMutationInput, Prisma.WorkspaceUserUncheckedUpdateManyWithoutDmGroupsInput>
}

export type WorkspaceUserUpsertWithoutDmGroupsCreatedInput = {
  update: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutDmGroupsCreatedInput, Prisma.WorkspaceUserUncheckedUpdateWithoutDmGroupsCreatedInput>
  create: Prisma.XOR<Prisma.WorkspaceUserCreateWithoutDmGroupsCreatedInput, Prisma.WorkspaceUserUncheckedCreateWithoutDmGroupsCreatedInput>
  where?: Prisma.WorkspaceUserWhereInput
}

export type WorkspaceUserUpdateToOneWithWhereWithoutDmGroupsCreatedInput = {
  where?: Prisma.WorkspaceUserWhereInput
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateWithoutDmGroupsCreatedInput, Prisma.WorkspaceUserUncheckedUpdateWithoutDmGroupsCreatedInput>
}

export type WorkspaceUserUpdateWithoutDmGroupsCreatedInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  messageSender?: Prisma.MessageUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUpdateManyWithoutWorkspaceUsersNestedInput
}

export type WorkspaceUserUncheckedUpdateWithoutDmGroupsCreatedInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messageSender?: Prisma.MessageUncheckedUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
}

export type WorkspaceUserCreateManyUserInput = {
  id?: string
  workspaceId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
}

export type WorkspaceUserUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  messageSender?: Prisma.MessageUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messageSender?: Prisma.MessageUncheckedUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkspaceUserCreateManyWorkspaceInput = {
  id?: string
  userId: string
  role?: $Enums.WorkspaceUserRole
  joinedAt?: Date | string
}

export type WorkspaceUserUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  messageSender?: Prisma.MessageUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messageSender?: Prisma.MessageUncheckedUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroups?: Prisma.DMGroupUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkspaceUserUpdateWithoutWorkspaceChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  messageSender?: Prisma.MessageUpdateManyWithoutSenderUserNestedInput
  dmGroups?: Prisma.DMGroupUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateWithoutWorkspaceChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messageSender?: Prisma.MessageUncheckedUpdateManyWithoutSenderUserNestedInput
  dmGroups?: Prisma.DMGroupUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateManyWithoutWorkspaceChannelInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkspaceUserUpdateWithoutDmGroupsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutWorkspaceUsersNestedInput
  messageSender?: Prisma.MessageUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateWithoutDmGroupsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  messageSender?: Prisma.MessageUncheckedUpdateManyWithoutSenderUserNestedInput
  workspaceChannel?: Prisma.WorkspaceChannelUncheckedUpdateManyWithoutWorkspaceUsersNestedInput
  dmGroupsCreated?: Prisma.DMGroupUncheckedUpdateManyWithoutCreatedByUserNestedInput
}

export type WorkspaceUserUncheckedUpdateManyWithoutDmGroupsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.EnumWorkspaceUserRoleFieldUpdateOperationsInput | $Enums.WorkspaceUserRole
  joinedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type WorkspaceUserCountOutputType
 */

export type WorkspaceUserCountOutputType = {
  messageSender: number
  workspaceChannel: number
  dmGroups: number
  dmGroupsCreated: number
}

export type WorkspaceUserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  messageSender?: boolean | WorkspaceUserCountOutputTypeCountMessageSenderArgs
  workspaceChannel?: boolean | WorkspaceUserCountOutputTypeCountWorkspaceChannelArgs
  dmGroups?: boolean | WorkspaceUserCountOutputTypeCountDmGroupsArgs
  dmGroupsCreated?: boolean | WorkspaceUserCountOutputTypeCountDmGroupsCreatedArgs
}

/**
 * WorkspaceUserCountOutputType without action
 */
export type WorkspaceUserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUserCountOutputType
   */
  select?: Prisma.WorkspaceUserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WorkspaceUserCountOutputType without action
 */
export type WorkspaceUserCountOutputTypeCountMessageSenderArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MessageWhereInput
}

/**
 * WorkspaceUserCountOutputType without action
 */
export type WorkspaceUserCountOutputTypeCountWorkspaceChannelArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkspaceChannelWhereInput
}

/**
 * WorkspaceUserCountOutputType without action
 */
export type WorkspaceUserCountOutputTypeCountDmGroupsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DMGroupWhereInput
}

/**
 * WorkspaceUserCountOutputType without action
 */
export type WorkspaceUserCountOutputTypeCountDmGroupsCreatedArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DMGroupWhereInput
}


export type WorkspaceUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  userId?: boolean
  role?: boolean
  joinedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  messageSender?: boolean | Prisma.WorkspaceUser$messageSenderArgs<ExtArgs>
  workspaceChannel?: boolean | Prisma.WorkspaceUser$workspaceChannelArgs<ExtArgs>
  dmGroups?: boolean | Prisma.WorkspaceUser$dmGroupsArgs<ExtArgs>
  dmGroupsCreated?: boolean | Prisma.WorkspaceUser$dmGroupsCreatedArgs<ExtArgs>
  _count?: boolean | Prisma.WorkspaceUserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workspaceUser"]>

export type WorkspaceUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  userId?: boolean
  role?: boolean
  joinedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workspaceUser"]>

export type WorkspaceUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  userId?: boolean
  role?: boolean
  joinedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workspaceUser"]>

export type WorkspaceUserSelectScalar = {
  id?: boolean
  workspaceId?: boolean
  userId?: boolean
  role?: boolean
  joinedAt?: boolean
}

export type WorkspaceUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workspaceId" | "userId" | "role" | "joinedAt", ExtArgs["result"]["workspaceUser"]>
export type WorkspaceUserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  messageSender?: boolean | Prisma.WorkspaceUser$messageSenderArgs<ExtArgs>
  workspaceChannel?: boolean | Prisma.WorkspaceUser$workspaceChannelArgs<ExtArgs>
  dmGroups?: boolean | Prisma.WorkspaceUser$dmGroupsArgs<ExtArgs>
  dmGroupsCreated?: boolean | Prisma.WorkspaceUser$dmGroupsCreatedArgs<ExtArgs>
  _count?: boolean | Prisma.WorkspaceUserCountOutputTypeDefaultArgs<ExtArgs>
}
export type WorkspaceUserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type WorkspaceUserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $WorkspaceUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkspaceUser"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    messageSender: Prisma.$MessagePayload<ExtArgs>[]
    workspaceChannel: Prisma.$WorkspaceChannelPayload<ExtArgs>[]
    dmGroups: Prisma.$DMGroupPayload<ExtArgs>[]
    dmGroupsCreated: Prisma.$DMGroupPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    workspaceId: string
    userId: string
    role: $Enums.WorkspaceUserRole
    joinedAt: Date
  }, ExtArgs["result"]["workspaceUser"]>
  composites: {}
}

export type WorkspaceUserGetPayload<S extends boolean | null | undefined | WorkspaceUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload, S>

export type WorkspaceUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkspaceUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkspaceUserCountAggregateInputType | true
  }

export interface WorkspaceUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkspaceUser'], meta: { name: 'WorkspaceUser' } }
  /**
   * Find zero or one WorkspaceUser that matches the filter.
   * @param {WorkspaceUserFindUniqueArgs} args - Arguments to find a WorkspaceUser
   * @example
   * // Get one WorkspaceUser
   * const workspaceUser = await prisma.workspaceUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkspaceUserFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkspaceUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkspaceUserClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkspaceUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkspaceUserFindUniqueOrThrowArgs} args - Arguments to find a WorkspaceUser
   * @example
   * // Get one WorkspaceUser
   * const workspaceUser = await prisma.workspaceUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkspaceUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkspaceUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkspaceUserClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkspaceUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceUserFindFirstArgs} args - Arguments to find a WorkspaceUser
   * @example
   * // Get one WorkspaceUser
   * const workspaceUser = await prisma.workspaceUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkspaceUserFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkspaceUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkspaceUserClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkspaceUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceUserFindFirstOrThrowArgs} args - Arguments to find a WorkspaceUser
   * @example
   * // Get one WorkspaceUser
   * const workspaceUser = await prisma.workspaceUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkspaceUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkspaceUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkspaceUserClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkspaceUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkspaceUsers
   * const workspaceUsers = await prisma.workspaceUser.findMany()
   * 
   * // Get first 10 WorkspaceUsers
   * const workspaceUsers = await prisma.workspaceUser.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workspaceUserWithIdOnly = await prisma.workspaceUser.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkspaceUserFindManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkspaceUser.
   * @param {WorkspaceUserCreateArgs} args - Arguments to create a WorkspaceUser.
   * @example
   * // Create one WorkspaceUser
   * const WorkspaceUser = await prisma.workspaceUser.create({
   *   data: {
   *     // ... data to create a WorkspaceUser
   *   }
   * })
   * 
   */
  create<T extends WorkspaceUserCreateArgs>(args: Prisma.SelectSubset<T, WorkspaceUserCreateArgs<ExtArgs>>): Prisma.Prisma__WorkspaceUserClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkspaceUsers.
   * @param {WorkspaceUserCreateManyArgs} args - Arguments to create many WorkspaceUsers.
   * @example
   * // Create many WorkspaceUsers
   * const workspaceUser = await prisma.workspaceUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkspaceUserCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkspaceUsers and returns the data saved in the database.
   * @param {WorkspaceUserCreateManyAndReturnArgs} args - Arguments to create many WorkspaceUsers.
   * @example
   * // Create many WorkspaceUsers
   * const workspaceUser = await prisma.workspaceUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkspaceUsers and only return the `id`
   * const workspaceUserWithIdOnly = await prisma.workspaceUser.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkspaceUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkspaceUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkspaceUser.
   * @param {WorkspaceUserDeleteArgs} args - Arguments to delete one WorkspaceUser.
   * @example
   * // Delete one WorkspaceUser
   * const WorkspaceUser = await prisma.workspaceUser.delete({
   *   where: {
   *     // ... filter to delete one WorkspaceUser
   *   }
   * })
   * 
   */
  delete<T extends WorkspaceUserDeleteArgs>(args: Prisma.SelectSubset<T, WorkspaceUserDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkspaceUserClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkspaceUser.
   * @param {WorkspaceUserUpdateArgs} args - Arguments to update one WorkspaceUser.
   * @example
   * // Update one WorkspaceUser
   * const workspaceUser = await prisma.workspaceUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkspaceUserUpdateArgs>(args: Prisma.SelectSubset<T, WorkspaceUserUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkspaceUserClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkspaceUsers.
   * @param {WorkspaceUserDeleteManyArgs} args - Arguments to filter WorkspaceUsers to delete.
   * @example
   * // Delete a few WorkspaceUsers
   * const { count } = await prisma.workspaceUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkspaceUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkspaceUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkspaceUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkspaceUsers
   * const workspaceUser = await prisma.workspaceUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkspaceUserUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkspaceUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkspaceUsers and returns the data updated in the database.
   * @param {WorkspaceUserUpdateManyAndReturnArgs} args - Arguments to update many WorkspaceUsers.
   * @example
   * // Update many WorkspaceUsers
   * const workspaceUser = await prisma.workspaceUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkspaceUsers and only return the `id`
   * const workspaceUserWithIdOnly = await prisma.workspaceUser.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkspaceUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkspaceUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkspaceUser.
   * @param {WorkspaceUserUpsertArgs} args - Arguments to update or create a WorkspaceUser.
   * @example
   * // Update or create a WorkspaceUser
   * const workspaceUser = await prisma.workspaceUser.upsert({
   *   create: {
   *     // ... data to create a WorkspaceUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkspaceUser we want to update
   *   }
   * })
   */
  upsert<T extends WorkspaceUserUpsertArgs>(args: Prisma.SelectSubset<T, WorkspaceUserUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkspaceUserClient<runtime.Types.Result.GetResult<Prisma.$WorkspaceUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkspaceUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceUserCountArgs} args - Arguments to filter WorkspaceUsers to count.
   * @example
   * // Count the number of WorkspaceUsers
   * const count = await prisma.workspaceUser.count({
   *   where: {
   *     // ... the filter for the WorkspaceUsers we want to count
   *   }
   * })
  **/
  count<T extends WorkspaceUserCountArgs>(
    args?: Prisma.Subset<T, WorkspaceUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkspaceUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkspaceUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkspaceUserAggregateArgs>(args: Prisma.Subset<T, WorkspaceUserAggregateArgs>): Prisma.PrismaPromise<GetWorkspaceUserAggregateType<T>>

  /**
   * Group by WorkspaceUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkspaceUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkspaceUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkspaceUserGroupByArgs['orderBy'] }
      : { orderBy?: WorkspaceUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkspaceUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkspaceUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkspaceUser model
 */
readonly fields: WorkspaceUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkspaceUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkspaceUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  messageSender<T extends Prisma.WorkspaceUser$messageSenderArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceUser$messageSenderArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  workspaceChannel<T extends Prisma.WorkspaceUser$workspaceChannelArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceUser$workspaceChannelArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkspaceChannelPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  dmGroups<T extends Prisma.WorkspaceUser$dmGroupsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceUser$dmGroupsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DMGroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  dmGroupsCreated<T extends Prisma.WorkspaceUser$dmGroupsCreatedArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceUser$dmGroupsCreatedArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DMGroupPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkspaceUser model
 */
export interface WorkspaceUserFieldRefs {
  readonly id: Prisma.FieldRef<"WorkspaceUser", 'String'>
  readonly workspaceId: Prisma.FieldRef<"WorkspaceUser", 'String'>
  readonly userId: Prisma.FieldRef<"WorkspaceUser", 'String'>
  readonly role: Prisma.FieldRef<"WorkspaceUser", 'WorkspaceUserRole'>
  readonly joinedAt: Prisma.FieldRef<"WorkspaceUser", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorkspaceUser findUnique
 */
export type WorkspaceUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceUser to fetch.
   */
  where: Prisma.WorkspaceUserWhereUniqueInput
}

/**
 * WorkspaceUser findUniqueOrThrow
 */
export type WorkspaceUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceUser to fetch.
   */
  where: Prisma.WorkspaceUserWhereUniqueInput
}

/**
 * WorkspaceUser findFirst
 */
export type WorkspaceUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceUser to fetch.
   */
  where?: Prisma.WorkspaceUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkspaceUsers to fetch.
   */
  orderBy?: Prisma.WorkspaceUserOrderByWithRelationInput | Prisma.WorkspaceUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkspaceUsers.
   */
  cursor?: Prisma.WorkspaceUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkspaceUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkspaceUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkspaceUsers.
   */
  distinct?: Prisma.WorkspaceUserScalarFieldEnum | Prisma.WorkspaceUserScalarFieldEnum[]
}

/**
 * WorkspaceUser findFirstOrThrow
 */
export type WorkspaceUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceUser to fetch.
   */
  where?: Prisma.WorkspaceUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkspaceUsers to fetch.
   */
  orderBy?: Prisma.WorkspaceUserOrderByWithRelationInput | Prisma.WorkspaceUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkspaceUsers.
   */
  cursor?: Prisma.WorkspaceUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkspaceUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkspaceUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkspaceUsers.
   */
  distinct?: Prisma.WorkspaceUserScalarFieldEnum | Prisma.WorkspaceUserScalarFieldEnum[]
}

/**
 * WorkspaceUser findMany
 */
export type WorkspaceUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * Filter, which WorkspaceUsers to fetch.
   */
  where?: Prisma.WorkspaceUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkspaceUsers to fetch.
   */
  orderBy?: Prisma.WorkspaceUserOrderByWithRelationInput | Prisma.WorkspaceUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkspaceUsers.
   */
  cursor?: Prisma.WorkspaceUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkspaceUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkspaceUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkspaceUsers.
   */
  distinct?: Prisma.WorkspaceUserScalarFieldEnum | Prisma.WorkspaceUserScalarFieldEnum[]
}

/**
 * WorkspaceUser create
 */
export type WorkspaceUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkspaceUser.
   */
  data: Prisma.XOR<Prisma.WorkspaceUserCreateInput, Prisma.WorkspaceUserUncheckedCreateInput>
}

/**
 * WorkspaceUser createMany
 */
export type WorkspaceUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkspaceUsers.
   */
  data: Prisma.WorkspaceUserCreateManyInput | Prisma.WorkspaceUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkspaceUser createManyAndReturn
 */
export type WorkspaceUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * The data used to create many WorkspaceUsers.
   */
  data: Prisma.WorkspaceUserCreateManyInput | Prisma.WorkspaceUserCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkspaceUser update
 */
export type WorkspaceUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkspaceUser.
   */
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateInput, Prisma.WorkspaceUserUncheckedUpdateInput>
  /**
   * Choose, which WorkspaceUser to update.
   */
  where: Prisma.WorkspaceUserWhereUniqueInput
}

/**
 * WorkspaceUser updateMany
 */
export type WorkspaceUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkspaceUsers.
   */
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateManyMutationInput, Prisma.WorkspaceUserUncheckedUpdateManyInput>
  /**
   * Filter which WorkspaceUsers to update
   */
  where?: Prisma.WorkspaceUserWhereInput
  /**
   * Limit how many WorkspaceUsers to update.
   */
  limit?: number
}

/**
 * WorkspaceUser updateManyAndReturn
 */
export type WorkspaceUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * The data used to update WorkspaceUsers.
   */
  data: Prisma.XOR<Prisma.WorkspaceUserUpdateManyMutationInput, Prisma.WorkspaceUserUncheckedUpdateManyInput>
  /**
   * Filter which WorkspaceUsers to update
   */
  where?: Prisma.WorkspaceUserWhereInput
  /**
   * Limit how many WorkspaceUsers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkspaceUser upsert
 */
export type WorkspaceUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkspaceUser to update in case it exists.
   */
  where: Prisma.WorkspaceUserWhereUniqueInput
  /**
   * In case the WorkspaceUser found by the `where` argument doesn't exist, create a new WorkspaceUser with this data.
   */
  create: Prisma.XOR<Prisma.WorkspaceUserCreateInput, Prisma.WorkspaceUserUncheckedCreateInput>
  /**
   * In case the WorkspaceUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkspaceUserUpdateInput, Prisma.WorkspaceUserUncheckedUpdateInput>
}

/**
 * WorkspaceUser delete
 */
export type WorkspaceUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
  /**
   * Filter which WorkspaceUser to delete.
   */
  where: Prisma.WorkspaceUserWhereUniqueInput
}

/**
 * WorkspaceUser deleteMany
 */
export type WorkspaceUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkspaceUsers to delete
   */
  where?: Prisma.WorkspaceUserWhereInput
  /**
   * Limit how many WorkspaceUsers to delete.
   */
  limit?: number
}

/**
 * WorkspaceUser.messageSender
 */
export type WorkspaceUser$messageSenderArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Message
   */
  select?: Prisma.MessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Message
   */
  omit?: Prisma.MessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MessageInclude<ExtArgs> | null
  where?: Prisma.MessageWhereInput
  orderBy?: Prisma.MessageOrderByWithRelationInput | Prisma.MessageOrderByWithRelationInput[]
  cursor?: Prisma.MessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MessageScalarFieldEnum | Prisma.MessageScalarFieldEnum[]
}

/**
 * WorkspaceUser.workspaceChannel
 */
export type WorkspaceUser$workspaceChannelArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceChannel
   */
  select?: Prisma.WorkspaceChannelSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceChannel
   */
  omit?: Prisma.WorkspaceChannelOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceChannelInclude<ExtArgs> | null
  where?: Prisma.WorkspaceChannelWhereInput
  orderBy?: Prisma.WorkspaceChannelOrderByWithRelationInput | Prisma.WorkspaceChannelOrderByWithRelationInput[]
  cursor?: Prisma.WorkspaceChannelWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WorkspaceChannelScalarFieldEnum | Prisma.WorkspaceChannelScalarFieldEnum[]
}

/**
 * WorkspaceUser.dmGroups
 */
export type WorkspaceUser$dmGroupsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DMGroup
   */
  select?: Prisma.DMGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DMGroup
   */
  omit?: Prisma.DMGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DMGroupInclude<ExtArgs> | null
  where?: Prisma.DMGroupWhereInput
  orderBy?: Prisma.DMGroupOrderByWithRelationInput | Prisma.DMGroupOrderByWithRelationInput[]
  cursor?: Prisma.DMGroupWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DMGroupScalarFieldEnum | Prisma.DMGroupScalarFieldEnum[]
}

/**
 * WorkspaceUser.dmGroupsCreated
 */
export type WorkspaceUser$dmGroupsCreatedArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DMGroup
   */
  select?: Prisma.DMGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DMGroup
   */
  omit?: Prisma.DMGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DMGroupInclude<ExtArgs> | null
  where?: Prisma.DMGroupWhereInput
  orderBy?: Prisma.DMGroupOrderByWithRelationInput | Prisma.DMGroupOrderByWithRelationInput[]
  cursor?: Prisma.DMGroupWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DMGroupScalarFieldEnum | Prisma.DMGroupScalarFieldEnum[]
}

/**
 * WorkspaceUser without action
 */
export type WorkspaceUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkspaceUser
   */
  select?: Prisma.WorkspaceUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkspaceUser
   */
  omit?: Prisma.WorkspaceUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkspaceUserInclude<ExtArgs> | null
}
